### ISSUE TITLE
TypeError: coc_nvim_1.workspace.onWillSaveUntil is not a function

### ISSUE THREAD

**Issue by wachri** [neoclide/coc-tslint-plugin#9]
`coc.nvim` introduce a breaking changes and removed the `onWillSaveUntil` with [v0.0.80](https://github.com/neoclide/coc.nvim/releases/tag/v0.0.80). It looks like that this plugin still use this function in the latest version. After updating I'm getting following error:

```
2020-12-23T16:04:44.707 ERROR (pid:11107) [extensions] - Error on active extension coc-tslint-plugin: TypeError: coc_nvim_1.workspace.onWillSaveUntil is not a function
```

**Comment by chemzqm** [comment]
Yes, it's broken

**Comment by Cocophotos** [comment]
Hi,

After upgrading I ran into that issue. I saw that you've fixed it 2 month ago, but the autoFixOnSave wasn't working. After some debugging, it appears to me that the coc.nvim CodeActionManager that provides the getCodeActions function may have changed (see [here](https://github.com/neoclide/coc.nvim/blob/22c0b6239d5c1079fdf9013c85829e796ee48e7d/src/provider/codeActionmanager.ts#L43)). 

In your fixAll.ts file, you treat the [map](https://github.com/neoclide/coc-tslint-plugin/blob/3a73cca6397ae9f5b67306750200f007818505de/src/fixAll.ts#L8) as it is a map, now it's an array. I've removed lines 9 to 12 and changed map to codeActions and it works fine when I save with the autoFixOnSave.

BTW, coc.nvim does not provide useful information about this error, since it seems (at least on Node 14) that this fails silently.

Hope it helps others and you can fix it.

Best,

**Comment by chemzqm** [comment]
I've made a fix, but use eslint instead is recommended.
